on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: npm

      - run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION="${{ github.ref_name }}"
          # Remove 'v' prefix from tag if present
          TAG_VERSION=${TAG_VERSION#v}

          echo "Package version: $PKG_VERSION"
          echo "Tag version: $TAG_VERSION"

          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Version mismatch between package.json ($PKG_VERSION) and git tag ($TAG_VERSION)"
            exit 1
          fi
          echo "✅ Version check passed"
      - run: npm ci
      - run: npm run build
      - run: npm run package
        env:
          RELEASE_VERSION: '${{ github.ref_name }}'
      - run: npm run publish
        env:
          PUBLISHER_TOKEN: ${{ secrets.VSCE_TOKEN }}
