name: test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.2

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        run: TRIVY_DISABLE_VEX_NOTICE=true xvfb-run -a npm test
