on:
  pull_request:
    branches:
      - master
      
name: Test extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install

      - name: Run tests
        run: npm test
